logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: books
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
